name: run-integration-tests
on:
  push:
    branches: [ main ]
jobs:
  run-integration-tests:
    env:
      AWS_SAM_STACK_NAME: ees-ci-integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: SAM Validate
        run: |
          sam validate
      - name: SAM Build
        run: |
          sam build
      - name: SAM Deploy Test Environment
        run: |
          sam deploy \
            --s3-bucket=${{ secrets.AWS_SAM_ARTIFACTS_BUCKET }} \
            --stack-name=$AWS_SAM_STACK_NAME \
            --region=${{ secrets.AWS_REGION }} \
            --no-confirm-changeset \
            --capabilities="CAPABILITY_IAM"
      - name: Run integration tests
        run: |
          pytest
      - name: Delete Test Environment
        run: |
          aws cloudformation delete-stack --stack-name $AWS_SAM_STACK_NAME